// createPost
export const CREATE_POST_MODAL_OPEN = "CREATE_POST_MODAL_OPEN"
export const CREATE_POST_MODAL_CLOSE = "CREATE_POST_MODAL_CLOSE"
export const GET_USERS_DATA = "GET_USERS_DATA"
export const GET_CURRENT_USER_DATA = "GET_CURRENT_USER_DATA"